[project]
name = "personal-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gigachat>=0.2.3",
    "langchain>=1.4.2",
    "langchain-gigachat>=0.5.1",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "pandas>=3.0.6",
    "pytest>=9.1.1",
]
